mngr:
    resource: "@MngrBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

homepage:
    pattern:   /
    defaults:  { _controller: AcmeHomeBundle:home:show }