<?php

namespace WorkersManager\MngrBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SheduleRepository extends EntityRepository
{
}
